// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgdrllvplplypfvzdcjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZHJsbHZwbHBseXBmdnpkY2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Njg0MzcsImV4cCI6MjA2MzM0NDQzN30.1UCRX9Wikro-aAC0PD7bdxCEvwxEsfXVl_zMZ2YXlg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);